security:

    providers:
        our_db_provider:
            entity:
                class: App\Entity\Admin
                property: pseudo

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            provider: our_db_provider
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                default_target_path: home
                always_use_default_target_path: true
                use_referer: true

            logout:
                path: logout
                target: home

    encoders:
        App\Entity\Admin:
            algorithm: bcrypt