security:
    providers:
        our_db_provider:
          entity:
                class: App\Entity\User
                property: pseudo
    firewalls:
        main:
            pattern: ^/
            provider: our_db_provider
            anonymous: ~
            user_checker: App\Security\AdminChecker
            form_login:
                login_path: login
                check_path: login
            #logout_on_user_change: true
            logout:
                path: logout
                target: home

    encoders:
        App\Entity\Participant:
            algorithm: bcrypt
    access_control:
        - {path: '^/admin', roles: ROLE_ADMIN}
