security:

    providers:
        prodiver_admin:
            entity:
                class: App\Entity\Admin
                property: pseudo
        provider_player:
            entity:
                class: App\Entity\Player
                property: pseudo

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            provider: prodiver_admin
            pattern: ^/admin
            anonymous: ~
            form_login:
                login_path: login_admin
                check_path: login_admin
                default_target_path: home_admin
                always_use_default_target_path: true
                use_referer: true

            logout:
                path: logout_admin
                target: login_admin

        player:
            provider: provider_player
            pattern: ^/player
            anonymous: ~
            form_login:
                login_path: login_player
                check_path: login_player
                default_target_path: player_show
                always_use_default_target_path: true
                use_referer: true

            logout:
                path: logout_player
                target: login_player

    encoders:
        App\Entity\Admin:
            algorithm: bcrypt
        App\Entity\Player:
            algorithm: bcrypt

    access_control:
            - { path: '^/admin/login$', roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: '^/player/login$', roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: '^/player/new$', roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: '^/admin', roles: ROLE_ADMIN }
            - { path: '^/player', roles: ROLE_PLAYER }
